# Discussion

This report represents a major step forward in collating disperate datasets to inform on the biodiversity of offshore habitats for U.S. wind energy development. Although other efforts have combined AquaMaps and the RedList range maps [@halpernIndexAssessHealth2012; @oharaAligningMarineSpecies2017], this work represents the first attempt to combine these datasets with higher resolution density surface models.

Although the latitudinal gradient in species richness going from high to low in a poleward direction has been well described [@raboskyInverseLatitudinalGradient2018], the order of magnitude difference in species richness between the Atlantic (698.6 species per pixel) and the other regions of Gulf of Mexico (38.9) or Pacific (15.5) is noticably stark. Given that the Pacific is a western-boundary current with upwelling, it is cooler and more productive than the other regions associated with warmer waters like the Gulf of Mexico and Southeast Atlantic.

The NOAA bottom trawl surveys represent one of the most authoritative, fishery-independent survey data for the United States demersal fish. These data were recently used for evaluating wind energy areas in the Northeast [@friedlandResourceOccurrenceProductivity2021] and species range shifts from climate change [@pinskyMarineTaxaTrack2013; @pinskyFishFisheriesHot2021; @maureaudAreWeReady2021]. NOAA recently transferred the interpolated biomass maps of species quantified from Pinsky’s [OceanAdapt](https://oceanadapt.rutgers.edu/) portal into the NOAA Distribution Mapping and Analysis Portal ([DisMap](https://apps-st.fisheries.noaa.gov/dismap/)). Using the same inverse-distance-weighting interpolation techniques we generated similar maps of species biomass, except for the BOEM planning regions. However, the spatial extent of these results do not span far enough offshore to encompass the full BOEM planning areas with expansive gaps in between. Ideally in future these data can be used to statistically model with environmental predictors predictions across the seascape, similar to Friedland et al. [-@friedlandResourceOccurrenceProductivity2021].

We hope this effort to collate the best available species distribution models into biodiversity metrics of conservation interest into the future. NOAA and NASA have invested in the Marine Biodiversity Observation Network ([MarineBON.org](https://marinebon.org)), which would be a sensible lead organization for atlas stewardship. Towards this end a Biodiversity Indicators working group is actively meeting to assess datasets and methods for combinatorial approaches for presenting this information towards satisfying the "America the Beautiful" initiative nationally and the "30 by 30" (30% conservation by 2030) effort globally.
