# Introduction

Development of offshore wind energy will be essential for providing renewable energy to mitigate climate change impacts, yet needs to be sited responsibly to avoid sensitive habitats. Acoustic impacts from construction and operation may negatively impact some species [@mooneyACOUSTICIMPACTSOFFSHORE2022]. Hard substrate provided by the platforms may actually benefit other species [@wilsonHabitatcreationPotentialOffshore2009]. Wind energy areas are under active development by the Bureau of Ocean Energy Management (BOEM) throughout the United States. This study will assess habitats for sensitivity throughout strategic parts of the US.

A couple fundamental questions driving this analysis are:

1. _How different are existing lease areas from the rest of the region?_ (_**intra-region**_)\
  Areas not already slated for the offshore wind leasing impact species and habitats less, so could be candidates for alternative future planning. Areas with designated military use and outside BOEM’s authority (e.g., National Marine Sanctuaries) need to be further excluded from consideration.

1.  _How different are existing lease areas from each other within a given region?_ (_**inter-lease**_)\
  Within the leasing process the most oversight can be exercised within existing lease areas, especially ones in the earlier stages of Proposed Sale Notices and Call Areas. Identifying less impacted lease areas may lend greater stakeholder support for development.
