# Technical

## Relational Database Structure

### Typography

-   `*`: wildcard indicating any value, such as `*.csv` for any file name ending in `.csv`
-   `{*}`: surrounding curly braces (`{}`) indicates variable substitution, e.g. `ds_{mdl_key}` would evaluate to the value `ds_am` for `mdl_key = "am"`, as in the dataset (`ds`) for AquaMaps (`am`)
-   `[*]`: surrounding brackets (`[]`) indicates an optional value, such as `[ply_grp]` is an optional column in the `ds_gm` table
-   `<*>`: surrounds the columns used to identify columns that uniquely identify (and index) each row
-   `...`: additional columns, unique to the table

The format below is of the following format where the top line of a bulleted list item describes the table and the columns in that table are directly below, nested in hierarchical order:

-   `{table name}` (`{description}`)\
    \<`{column 1}`, `{column 2}`\>, `{column 3}`, `...`

### Database Naming Conventions

-   Use all **lower-case** column names with underscores (i.e. from using `janitor::clean_names()`) to prevent need to quote SQL statements.
-   For short unique **identifiers** use suffix `*_id` for integer and `*_key` for short text.

### Models Based on Polygons

Models based on polygons have an attribute table that may contain multiple values of interest. The normalized form of the database should not require repeating the geometry for each polygon to reproduce the original dataset that may be shared across values for an individual model as well as across multiple models. If models in the dataset use more than one collection of polygons, then the polygon group `ply_grp` field is optionally used to differentiate which set of polygons to use.

All features are projected to the geographic (`EPSG:4326`) coordinate reference system for [`leaflet` R package visualization of polygons](https://rstudio.github.io/leaflet/shapes.html) with "slippy" basemaps (e.g. "Esri.OceanBasemap" at [Leaflet Providers](https://leaflet-extras.github.io/leaflet-providers/preview)).

-   `datasets`\
    \<`ds_key`\>, `...`

-   `cells_ds_ply` (cells to dataset polygons)\
    \<`ds_key`, `ply_id`, `cell_id`\>

-   `ds_{ds_key}` (dataset model attributes)\
    \<`ds_key`, `mdl_id`\>, `aphia_id`, `fld_ply_val`, `val_type`, `...`

-   `ds_{ds_key}_plys` (dataset polygon attributes, including values)\
    \<`ds_key`, `ply_id`\>, `val` = `{fc_flds}`, `...`

### Models Based on Rasters

All rasters are projected to web Mercator (`EPSG:3857`) coordinate reference system for [`leaflet` R package visualization of rasters](https://rstudio.github.io/leaflet/raster.html) with "slippy" basemaps (e.g. "Esri.OceanBasemap" at [Leaflet Providers](https://leaflet-extras.github.io/leaflet-providers/preview)). Since the variable is usually continuous, new values may be interpolated to the web Mercator raster with `method = "bilinear"` option (versus `method = "nearest"`). Because of this, the value is directly stored in the `_cells_rast` table for all raster models (versus a lookup of OffHab cell_ids to the original raster's pixel).

-   `datasets` \<`ds_key`\>, ...

-   `ds_cells_rast` (cells to dataset pixel values)\
    \<`ds_key`, `mdl_id`, `cell_id`\>, `val`

-   `mdls_{ds_key}` (dataset model attributes)\
    \<`ds_key`, `mdl_id`\>, `aphia_id`, `val_type`, `...`

### Future Development

1.  Add columns to handle relationships between models, such as uncertainty (e.g. `sd`/`cv`/ `ci95pct` / `ci5pct`; not using yet) associated with which density:
    -   `{mdl_key}_mdls.`: `mdl_related` \| `mdl_relationship`
2.  Add value transformation column (`val_transform`) to `{mdl_key}_mdls` to standardize values from original to `val_type` (not using yet since all relative so far):
    -   `oa_mdls.val_transform`: $val^3$
    -   `du_mdls.val_transform` $val/100$
